[package]
name = "arcaders-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["image", "unsafe_textures", "ttf"]

[dependencies.rand]
version = "0.8.5"